### PR TITLE
WIP: New generation

### PR DESCRIPTION
**Pull request by neonxp**
Cleanup code
New tokenizer (without regexes!  🎉)
All tests passing 👍 
Small API changes 😞
Zero-division by default throws exceptions (See Readme). 
@phpfui need your thoughts about that all

### CODE REVIEW

**Comment by phpfui** [comment]
Initial thoughts are it looks good.  I'll look at it more over this weekend, but I like the new parser algorithm on first glance. The better way for sure, but I did not want to refactor.

If we are going to 7.1 for sure, we should add types to all parameters and typed return values.

Should be a new version.  2.0 probably.

**Comment by neonxp** [comment]
Yes, it will be new version (because changed user API). I will add types at weekend.

**Comment by neonxp** [comment]
Some comparsions.
Tests run time:
image
Memory:  
Master: 18.00 MB
NG: 14.00 MB

**Comment by phpfui** [comment]
Nice!

Bruce

**Comment by phpfui** [comment]
Alex,

This mostly looks good.

I would say we should leave the members (variables, operators, and functions) private and keep the accessor functions.  This is pretty standard OO practice (unless you learned JavaScript first!).  Also it becomes a breaking change for people, so they will be annoyed and less likely to upgrade.  They were always private, so we should continue with that, as it was the correct original approach.  I had to flesh them out at first, but notice I did not say we should make them public at the time.  This affords us some flexibility in the implementation later on with out having to bump the major version again.

I don't have a problem changing the Operator stuff, that is more of an internal class, and if you needed to update something there, you would probably be best served going to the new model.

Also, while I agree an exception on divide by zero should be the default, we should keep the ability to turn it off, as your original divide by zero is zero is not a bad solution, and some people may be depending on that.  So to port to the new version, they would have to call the function to change behavior, a minor annoyance to gain the better default.

And add in parameter types and return type where ever possible.  This is a great 7.1 feature. I use it ALL the time. Saves grief every day.

So the only really breaking change would be division by zero if you are using the base MathExecutor class.  Maybe we rename the function so it is not silent.

**Comment by neonxp** [comment]
Ok, I will do that. Good correction.

**Pull request merged**
