### PR TITLE
add new functions and aliases to the old functions

### PR DESCRIPTION
**Pull request by diman3210**

### CODE REVIEW

**Comment by phpfui** [comment]
I thought you forgot about us!  This is looking good.  I will review this weekend and probably publish by Monday.

Thanks for the contribution.

**Comment by phpfui** [comment]
Actually there is one improvement you can add to this PR, which is some unit tests.

See the tests/MathTest.php file and the providerExpressions method.  You can add simple  expressions there that are the same in PHP and MathExecutor.

We should probably add another provider and test for where the PHP and MathExecutor expressions are not the same.  I'll see if I can add that to this PR, over the weekend.  These types of tests should probably just have the MathExecutor expression and the computed answer.

**Comment by phpfui** [comment]
Here is the code you can add:
```php
    /**
     * @dataProvider providerExpressionValues
     */
    public function testCalculatingValues($expression, $value)
    {
        $calculator = new MathExecutor();

        try {
            $result = $calculator->execute($expression);
        } catch (Exception $e) {
           $this->fail(sprintf("Exception: %s (%s:%d), expression was: %s", get_class($e), $e->getFile(), $e->getLine(), $expression));
        }
        $this->assertEquals($value, $result, "${expression} did not evaluate to {$value}");
    }

    /**
     * Expressions data provider
     *
     * Most tests can go in here.  The idea is that each expression will be evaluated by MathExecutor and by PHP with eval.
     * The results should be the same.  If they are not, then the test fails.  No need to add extra test unless you are doing
     * something more complex and not a simple mathmatical expression.
     */
    public function providerExpressionValues()
    {
     return [
         ['arcsec(4)', 1.3181160716528],
       ];
    }
```
Then add your tests to providerExpressionValues or providerExpressions depending on if they are the same in PHP and MathExecutor.

**Comment by neonxp** [comment]
Hi, fellas!
May be better improvement will be implement function like `$executor->addAlias('log', 'ln')` to not repeat functions implementation?
I have no strong position about this, but I think, that better has aliases, not copies. How do you think?

**Comment by phpfui** [comment]
**addAlias** makes sense to me for true aliases. @diman3210 let me know if you want to do this.  Or I can once this merges.

**Comment by neonxp** [comment]
Yes, I can approve too, if @diman3210 decides that this implementation is good enough. 🤷🏻‍♂️

**Comment by diman3210** [comment]
> **addAlias** makes sense to me for true aliases. @diman3210 let me know if you want to do this. Or I can once this merges.

Hi, I don't mind. You do it.

**Pull request merged**
