### PR TITLE
Drop php74

### PR DESCRIPTION
**Pull request by phpfui**

### CODE REVIEW

**Comment by neonxp** [comment]
https://github.com/neonxp/MathExecutor/pull/57 just 2 years 7.4 lived in project :)

**Comment by phpfui** [comment]
Alex, good to see you are still around!

https://blog.phpfui.com/the-costs-of-legacy-support

**Comment by neonxp** [comment]
I sometimes lazily look at what's going on here :) I receive notifications about events.

**Comment by phpfui** [comment]
Still the best calculator package out there.  456,345 downloads so far!

**Comment by neonxp** [comment]
Wow! It's amazing :) I can't believe that my little project, which I did as a student just for fun, turned out to be so useful!

**Comment by phpfui** [comment]
It was the best one out there when I needed it. The others did not have long variable names (like single character for mathematicians), and other issues. Definitely a needed package. You can't just do an eval() on user input!

**Comment by neonxp** [comment]
I am glad that the project has met the requirements 👍🏻

**Comment by phpfui** [comment]
It did.  And I don't even use it professionally any more.  Now I just maintain it because it is a great project.  And I just remembered, I have to update composer.json to 8.0 from 7.4.  Missed that.

**Pull request merged**
