### PR TITLE
Two more tests + some code refactoring

### PR DESCRIPTION
**Pull request by javiermarinros**

### CODE REVIEW

**Comment by phpfui** [comment]
Javier,

This looks good, but the workflow is now requiring a code style.  Not sure when that got added, but it is a good thing.  Also, I had an issue with PHPCSFixer throwing errors yesterday under Windows, so I added an explicit configuration.

So run it at a command line with

vendor/bin/php-cs-fixer fix

Then check in the changes.  I think it may be configured to remove useless comments (one of my pet peeves) and a few other things, like YODA notation for if statements (a good thing), that vary from the defaults.

And thanks for the code cleanup! And if you are not using PHP-CS-Fixer for all your projects, you should. Great tool.

Also note the master branch is now 7.4, another good thing.

**Comment by javiermarinros** [comment]
Thank you @phpfui for your suggestions. I ran the PHP-CS-Fixer command and committed the changes. It removed two @var `mixed` that don't add syntactical information, but those annotations could be useful in the future if the master branch is switched to PHP 8, as the `mixed` type is available since that version, and also PHPStan complains when it founds vars and params with no type at all. Maybe the PHP-CS-Fixer configuration can be changed to allow those annotations.

On the other hand, the `testUnsupportedOperands` test is failing under PHP 7 because of the way PHP handles those operands, I've added a condition to test the mayor version and run the test only on PHP 8+ environments.

**Comment by phpfui** [comment]
Thanks, will take a look at it by early next week.  I think the Windows tests don't run the PHP-CD-Fixer tests.

**Comment by phpfui** [comment]
Turns out the errors were an extra line in the properties in the Token class.  Now fixed and merged.

Thanks for the contributions!

**Pull request merged**
